<?php
namespace gamboamartin\cobranza\models;
use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class cob_deuda extends _modelo_parent {

    public function __construct(PDO $link){
        $tabla = 'cob_deuda';
        $columnas = array($tabla=>false,'cob_concepto'=>$tabla,'cob_cliente'=>$tabla);
        $campos_obligatorios[] = 'descripcion';
        $campos_obligatorios[] = 'descripcion_select';

        $tipo_campos['codigos'] = 'cod_1_letras_mayusc';

        $columnas_extra['cob_deuda_n_pagos'] = /** @lang sql */
            "(SELECT COUNT(*) FROM cob_pago WHERE cob_pago.cob_deuda_id = cob_pago.id)";


        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, tipo_campos: $tipo_campos);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion', 'fecha_vencimiento')): array|stdClass
    {

        if(!isset($this->registro['descripcion'])){
            $cob_concepto = (new cob_concepto(link: $this->link))->registro($this->registro['cob_concepto_id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error ol obtener cob_concepto', data: $cob_concepto);
            }

            $cob_cliente = (new cob_cliente(link: $this->link))->registro($this->registro['cob_cliente_id']);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error ol obtener cob_cliente', data: $cob_cliente);
            }

            $descripcion = $this->registro['monto'].' '.$this->registro['fecha_vencimiento'].' ';
            $descripcion .= $cob_concepto['cob_concepto_descripcion'].' ';
            $descripcion .= $cob_concepto['cob_tipo_concepto_descripcion'].' ';
            $descripcion .= $cob_cliente['cob_cliente_nombre'].' ';
            $descripcion .= $cob_cliente['cob_cliente_ap'].' ';
            $descripcion .= $cob_cliente['cob_cliente_am'].' ';
            $descripcion .= $cob_cliente['org_sucursal_descripcion'].' ';


            $this->registro['descripcion'] = $descripcion;
        }
        $r_alta_bd = parent::alta_bd($keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta deuda', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }


}